#####CARGAR LIBRERIAS#####
library(readxl)
library(car)
library(ggplot2)
library(reshape)
library(gridExtra)
library(AER)
library(memisc)
library(lmtest)
library(texreg)
library(orcutt)
library(PerformanceAnalytics)
library(tidyverse, warn = FALSE)
library(corrplot)

